### ISSUE TITLE
？？

### ISSUE THREAD

**Issue by NIHAOAWA** [zhiziqixingdeng/zhizi-game#1]
快改改README，在来个管理员系统，否则没人会用这个的，别再自以为是了。没有管理员系统的一点都不好

**Comment by zhiziqixingdeng** [comment]
管理员系统有用吗，我一些单机游戏，那需要管理系统吗？

**Comment by zhiziqixingdeng** [comment]
> 快改改README，在来个管理员系统，否则没人会用这个的，别再自以为是了。没有管理员系统的一点都不好

哪里不好，单机游戏不需要的，都是人机在陪玩，不会有骂人之类的违规行为，需要管理系统干啥

**Comment by NIHAOAWA** [comment]
> > 快改改README，在来个管理员系统，否则没人会用这个的，别再自以为是了。没有管理员系统的一点都不好
> 
> 哪里不好，单机游戏不需要的，都是人机在陪玩，不会有骂人之类的违规行为，需要管理系统干啥

**Comment by NIHAOAWA** [comment]
谁告诉你单机游戏不需要的

**Comment by zhiziqixingdeng** [comment]
> 谁告诉你单机游戏不需要的

所以到底需要干什么呢

**Comment by zhiziqixingdeng** [comment]
6

**Comment by zhiziqixingdeng** [comment]
快点说啊，别在这里乱瞎说
